version: '3.4'

services:
    rabbit:
        image: rabbitmq:3-management
        container_name: container_rabbitmq
        ports:
            - "15672:15672"
            - "5672:5672"
        environment:
            RABBITMQ_DEFAULT_USER: "guest"
            RABBITMQ_DEFAULT_PASS: "guest"
            RABBITMQ_DEFAULT_VHOST: "/"
        healthcheck:
            test: ["CMD", "rabbitmqctl", "status"]
            interval: 30s
            timeout: 10s
            retries: 3
        networks:
            - net-market

    angular:
        image: angular
        build:
            context: ./angular-16-dashboard
            dockerfile: Dockerfile
        container_name: container_angular
        ports:
            - "4200:80"
        environment:
            RABBITMQ_HOST: rabbit
            RABBITMQ_PORT: 5672
            RABBITMQ_CREDENTIALS_USER: guest
            RABBITMQ_CREDENTIALS_PASSWORD: guest
            API_KEY: development
            BACKEND_URL_FASTAPI: fastapi
            BACKEND_URL_EXPRESS: express
        networks:
            - net-market

    react:
        image: react
        build:
            context: ./react-18-dashboard
            dockerfile: Dockerfile
        container_name: container_react
        ports:
            - "3200:3000"
        environment:
            RABBITMQ_HOST: rabbit
            RABBITMQ_PORT: 5672
            RABBITMQ_CREDENTIALS_USER: guest
            RABBITMQ_CREDENTIALS_PASSWORD: guest
            API_KEY: development
            BACKEND_URL_FASTAPI: fastapi
            BACKEND_URL_EXPRESS: express
        networks:
            - net-market

    fastapi:
        image: fastapi
        build:
            context: ./fastapi-dashboard
            dockerfile: Dockerfile
        container_name: container_fastapi
        ports:
            - "8000:80"
        environment:
            RABBITMQ_HOST: rabbit
            RABBITMQ_PORT: 5672
            RABBITMQ_CREDENTIALS_USER: guest
            RABBITMQ_CREDENTIALS_PASSWORD: guest
            API_KEY: development
            EMAIL_SERVER: smtp.office365.com
            EMAIL_PORT: 587
            EMAIL_USERNAME: development_market@hotmail.com
            EMAIL_PASSWORD: Development
        networks:
            - net-market

    express:
        image: express
        build:
            context: ./express-dashboard
            dockerfile: Dockerfile
        container_name: container_express
        ports:
            - "3000:80"
        environment:
            RABBITMQ_HOST: rabbit
            RABBITMQ_PORT: 5672
            RABBITMQ_CREDENTIALS_USER: guest
            RABBITMQ_CREDENTIALS_PASSWORD: guest
        networks:
            - net-market

networks:
    net-market: