version: '3.4'

services:
    rabbit:
        image: rabbitmq:3-management
        container_name: container_rabbitmq
        ports:
            - "15672:15672"
            - "5672:5672"
        environment:
            RABBITMQ_DEFAULT_USER: "guest"
            RABBITMQ_DEFAULT_PASS: "guest"
            RABBITMQ_DEFAULT_VHOST: "/"
        healthcheck:
            test: ["CMD", "rabbitmqctl", "status"]
            interval: 30s
            timeout: 10s
            retries: 3
        networks:
            - net-market